server {
    listen 80;

    # 1. Sirve los archivos estáticos de tu plataforma (React/Vite)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto evita el error 404 cuando el usuario recarga la página
        try_files $uri $uri/ /index.html; 
    }

    # 2. Redirige todas las peticiones de la API a tu servidor Node.js
    location /api/ {
        # 'server' es el nombre que le dimos al backend en docker-compose.yml
        proxy_pass http://server:3001/api/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}